spring:
    profiles:
        active: localgroup

---

spring:
    profiles:
        group:
            localgroup: common, local

---

##########################################profiles : common
spring:
    thymeleaf:
        enabled: false
    servlet:
        multipart:
            enabled : false

    mvc:
        static-path-pattern: /static/**
    web:    
        resources:
            static-locations: classpath:/static/
            add-mappings: true
    config:
        activate:
            on-profile: common

mybatis:
    configuration:
        db1:
            map-underscore-to-camel-case: true
            use-column-label : true
            default-statemet-timeout: 25000
            jdbc-type-for-null : 'NULL'

server:
    tomcat:
        additional-tld-skip-patterns: "serializer.jar"