spring:
    config:
        activate:
            on-profile: local

ddit:
    setting:
        charset: UTF-8
        max-upload-size: 500

---

spring:
    config:
        activate:
            on-profile: local

ddit:
    info:
        app-name: local
    log:
        login: true
        menu: false

---